GET http://localhost:8090/todos

###

POST http://localhost:8090/todos
Content-Type: application/json

{
  "content":"Created Todo"
}

###

DELETE http://localhost:8090/todos?ids=1,2,3

###

PATCH http://localhost:8090/todos/4/content
Content-Type: application/json

{
  "content":"aaaaaa"
}

###
PATCH http://localhost:8090/todos/4/completion
Content-Type: application/json

{
  "isComplete": true
}